-- # 1. 기본 유저 및 권한 관련 테이블
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, PHONE, EMAIL, ADDRESS, USER_TYPE, TOTAL_TOKENS, JOIN_DATE)
VALUES (1, 'alice', 'pass1', '010-0000-0001', 'alice@example.com', '서울시 강남구', '해결사', 305, SYSDATE - 10);
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, PHONE, EMAIL, ADDRESS, USER_TYPE, TOTAL_TOKENS, JOIN_DATE)
VALUES (2, 'bob', 'pass2', '010-0000-0002', 'bob@example.com', '서울시 서초구', '의뢰인',  497, SYSDATE - 20);
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, PHONE, EMAIL, ADDRESS, USER_TYPE, TOTAL_TOKENS, JOIN_DATE)
VALUES (3, 'carol', 'pass3', '010-0000-0003', 'carol@example.com', '서울시 송파구', '관리자',  120, SYSDATE - 30);

-- # 2.1. 지역 테이블
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (1, '서울');
INSERT INTO REGION (REGION_ID, REGION_NAME) VALUES (2, '부산');

-- # 2.2. 구역 테이블
INSERT INTO DISTRICT (DISTRICT_ID, REGION_ID, DISTRICT_NAME) VALUES (1, 1, '강남구');
INSERT INTO DISTRICT (DISTRICT_ID, REGION_ID, DISTRICT_NAME) VALUES (2, 1, '서초구');
INSERT INTO DISTRICT (DISTRICT_ID, REGION_ID, DISTRICT_NAME) VALUES (3, 2, '해운대구');

-- # 3. 퀘스트 관련 테이블
INSERT INTO QUESTS (QUEST_ID, USER_ID, TITLE, CATEGORY, CONTENT, STATUS, PROGRESS, LATITUDE, LONGITUDE, ADDRESS, LOCATION, START_DATE, END_DATE, VIEW_COUNT, REWARD_TOKENS)
VALUES (1, 2, '강아지 산책 시켜주세요', '반려동물', '퇴근 시간 전에 부탁드립니다.', '대기', 0, 37.4979, 127.0276, '서울 강남구 테헤란로', '강남구', SYSDATE, SYSDATE + 1, 5, 100);

-- # 4. 퀘스트 할 일 목록 Task 테이블
INSERT INTO QUEST_TASK (TASK_ID, QUEST_ID, DESCRIPTION, IS_CHECKED)
VALUES (1, 1, '강아지 산책 30분', '0');

-- # 5.1. 퀘스트 신청자 정보 테이블
INSERT INTO QUEST_APPLICATION (APPLICATION_ID, QUEST_ID, USER_ID, STATUS)
VALUES (1, 1, 1, '대기');

-- # 6. 퀘스트 해결내역 테이블
INSERT INTO QUEST_RESOLVE (RESOLVE_ID, QUEST_ID, USER_ID, STATUS)
VALUES (1, 1, 1, '완료');

-- 7. 태그 및 추천 키워드
INSERT INTO QUEST_TAG (TAG_ID, KEYWORD, TAG_TEXT) VALUES (1, '반려동물', '산책');
INSERT INTO QUEST_TAG (TAG_ID, KEYWORD, TAG_TEXT) VALUES (2, '생활', '청소');

-- 8. 광고 테이블
INSERT INTO ADVERTISE (AD_ID, TITLE, IMAGE_URL, LINK_URL, POSITION)
VALUES (1, '지금 가입하면 100포인트 지급!', 'http://example.com/img1.jpg', 'http://example.com', '메인상단');

-- 9.1. 결제 기록 관련 테이블
INSERT INTO PAYMENTS (PAYMENT_ID, USER_ID, NICKNAME, CURRENT_BALANCE, TOTAL_CHARGED, TOTAL_WITHDRAWN, STATUS)
VALUES (1, 2, 'bob', 1000, 1500, 500, '정상');

-- 9.2. 코인 기록 관련 테이블
INSERT INTO COIN_HISTORY (HISTORY_ID, USER_ID, AMOUNT, TYPE, QUEST_ID)
VALUES (1, 2, -100, '퀘스트 요청', 1);
INSERT INTO COIN_HISTORY (HISTORY_ID, USER_ID, AMOUNT, TYPE, QUEST_ID)
VALUES (2, 1, 100, '퀘스트 보상', 1);

-- 10. 사용자 문의 테이블
INSERT INTO QUESTIONS (QUESTION_ID, TITLE, USER_ID, ANSWER_STATUS)
VALUES ('Q001', '앱 설치 오류 문의', 2, '미답변');
